### PR TITLE
Test setup

### PR DESCRIPTION
**Pull request by anuragkapur**
Static checks, automated tests and CI has been setup. The developer guide section of README contains documentation of this setup.

### CODE REVIEW

**Comment by adeas31** [comment]
Does the frameworks handle negative XY values?

Modelica uses a co-ordinate system for each model which is by defauly (-100, -100) to (100, 100) which means (0, 0) is center of view instead of left top. https://specification.modelica.org/v3.4/Ch18.html see section  `18.6.1.1 Coordinate Systems`.

**Comment by anuragkapur** [comment]
@adeas31 - yes, negative values are allowed. The X, Y coordinate values ultimately get translated to CSS Margin values, which supports negative values. Ref: https://www.w3schools.com/css/css_margin.asp

**Review by adeas31 — COMMENTED** [review]
LGTM just a general note. We should make concrete commits to the repository. Commits like `fixed typo` etc. should be squashed in one commit. We already have around 80 commits on the repository. When working on the PR it makes sense to have several commits but once it is ready to be merged in then we should update it to more concrete commits by squashing several commits.

**Review by adrpo — APPROVED** [review]
OK by me.

**Comment by anuragkapur** [comment]
Sure, @adeas31 - happy to stick to conventions used across OM projects. When merging this PR, 

1. An option available is: "Squash and Merge". This will convert the 21 commits on this branch to 1 commit on master for all this work. Should I use that option?
2. Alternatively, I can squash "some" of the 21 commits - this is tricker though.. and subjective as different people might have a different take on what should be squashed and what shouldn't. Example: should only "fix typo" type commits be squashed? What else should be squashed etc? 

Which option do you recommend? I'll be happy to use either of the two options. If option:2, we should probably create some guidance on what should be squashed and what should be kept as is.. Maybe option:1 is simplest to keep a clean commit history on master?

**Comment by adeas31** [comment]
Yes option 1 with **Squash and Merge** is good. When doing so you can edit the commit message and can make it better for commit history.

**Pull request merged**
